-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["paddleL"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "pLeft", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -33, -2.5  ,  -28, -13.5  ,  33, 11.5  }
                    }
                    
                    
                    
		}
		
		, 
		["ball"] = {
                    
		}
		
		, 
		["bg"] = {
                    
		}
		
		, 
		["bumper"] = {
                    
		}
		
		, 
		["credits"] = {
                    
		}
		
		, 
		["creditsBtn"] = {
                    
		}
		
		, 
		["hitBall"] = {
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    radius = 16.031
                    }
                    
                    
		}
		
		, 
		["hitLine"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -13.5, -54  ,  -5.5, -49  ,  19.5, 38  ,  0.5, 45  ,  -23.5, -42  ,  -22.5, -52  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   14.5, 51  ,  6.5, 51  ,  0.5, 45  ,  19.5, 38  ,  20.5, 45  }
                    }
                    
                    
                    
		}
		
		, 
		["l1"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -41, 107  ,  -41, -107  ,  -10, -107  ,  41, 72  ,  7, 106  }
                    }
                    
                    
                    
		}
		
		, 
		["l2"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   21, 13  ,  9, 28  ,  -23, 30  ,  -23, -30  ,  23, -30  }
                    }
                    
                    
                    
		}
		
		, 
		["l3"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -14.5, 57  ,  -14.5, -57  ,  14.5, -57  ,  14.5, 57  }
                    }
                    
                    
                    
		}
		
		, 
		["l4"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -62.5, 46.5  ,  -62.5, -46.5  ,  -32.5, -46.5  ,  62.5, 46.5  }
                    }
                    
                    
                    
		}
		
		, 
		["lBtn"] = {
                    
		}
		
		, 
		["paddleR"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   33, -2.5  ,  -31, 9.5  ,  30, -12.5  }
                    }
                    
                    
                    
		}
		
		, 
		["playBtn"] = {
                    
		}
		
		, 
		["r1"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -41, 72  ,  9, -105  ,  41, -107  ,  41, 107  ,  -6, 107  }
                    }
                    
                    
                    
		}
		
		, 
		["r2"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   23, -30  ,  23, 30  ,  -7, 30  ,  -21, 13  ,  -23, -30  }
                    }
                    
                    
                    
		}
		
		, 
		["r3"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -14.5, 57  ,  -14.5, -57  ,  14.5, -57  ,  14.5, 57  }
                    }
                    
                    
                    
		}
		
		, 
		["r4"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   25.5, -40.5  ,  62.5, -46.5  ,  62.5, 46.5  ,  -62.5, 46.5  }
                    }
                    
                    
                    
		}
		
		, 
		["rBtn"] = {
                    
		}
		
		, 
		["title"] = {
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

